### ISSUE TITLE
[Enhancement] Setting Walltaker per Monitor

### ISSUE THREAD

**Issue by WilliDieEnte** [PawCorp/walltaker-desktop-client#27]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to set Walltaker to a specific Monitor, not just to all

**Describe the solution you'd like**
I've never done stuff like this before, so I don't know any guaranteed way to make it work.

**Describe alternatives you've considered**
Not using Walltaker? xd
I've tried to use Wallpaper engine, but it gets overwritten with each Wallpaper change

**Additional context**
None, it's just a suggestion.

**Comment by oddpawsx** [comment]
Thank you for your suggestion! At this time, it looks like the golang wallpaper module we're using does not support setting wallpapers individually per monitor, and I haven't come across an alternative library that has what we need that supports this kind of feature. Because of this, closing as wontfix.

**Comment by Pauly2000** [comment]
You said you have Wallpaper Engine
I made a Wallpaper Enginge Wallpaper that works for me.

Have fun:
www.mediafire.com/file/v2szfr1spuvnccd
